name: AtomicConomy
version: 0.1
main: com.atomiccraft.AtomicConomy

commands:
   money:
      description: This is the /money command
      usage: /money [player]
      permission: AtomicConomy.money
      permission-message: You don't have permission to perform a /money command!
   acon:
      description: The /acon command
      usage: /acon version
      permission: AtomicConomy.acon
      permission-message: You don't have permission to perform a /acon command!      